# Generated by Django 4.2 on 2023-04-17 17:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='the phone no must be entered in the format +000 up to 15 digits', regex='^\\+?1?\\d{9,15}')])),
                ('checkin', models.DateField(default=datetime.datetime.now)),
                ('checkout', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.room')),
            ],
        ),
    ]
