# Generated by Django 4.2 on 2023-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('family', 'family'), ('suite', 'suite')], default='single', max_length=20)),
                ('free', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('feature', models.ManyToManyField(to='info.feature')),
            ],
        ),
    ]
